[package]
name = "diagrams"
version = "0.1.0"
edition = "2021"

[dependencies]
proc_macros = { path = "src/proc_macros" }
glow = "0.12.3"
glutin = "0.29.1"
nalgebra-glm = "0.18.0"
imgui = {version = "0.11.0", features = ["tables-api"]}
imgui-winit-support = "0.11.0"
imgui-glow-renderer = "0.11.0"